# Generated by Django 3.1.6 on 2021-06-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210621_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='catagorey',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='pickupordelivery',
            new_name='deliveryorpickup',
        ),
    ]
