# Generated by Django 3.1.6 on 2021-06-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_donation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='deliveryorpickup',
        ),
        migrations.AddField(
            model_name='donation',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
