# Generated by Django 3.1.6 on 2021-06-24 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20210623_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdetails',
            new_name='UserDetail',
        ),
    ]
