# Generated by Django 3.1.6 on 2021-06-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210624_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='requests',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
