# Generated by Django 3.1.6 on 2021-07-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_donation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
