# Generated by Django 3.1.6 on 2021-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210712_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
