# Generated by Django 3.1.6 on 2021-07-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210712_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='image',
        ),
    ]
