# Generated by Django 3.1.6 on 2021-07-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_donation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='datedonated',
        ),
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
