# Generated by Django 3.1.6 on 2021-07-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210712_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
