# Generated by Django 3.1.6 on 2021-07-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210712_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
