# Generated by Django 3.1.6 on 2021-07-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_donation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
